apiVersion: v1
kind: Service
metadata:
  name: static-site-service
spec:
  selector:
    app: static-site
  type: NodePort  # Expose it as a NodePort service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31345  # Change if needed

